
PROGRAM MAIN
USE GLOBAL
IMPLICIT NONE

  PC=0.0
  U=0.0
  V=0.0
  T=0.0 
  P=0.0   


CSUM=1.0
USUM=1.0
VSUM=1.0
TSUM=1.0
OUTCOUNTER=0
 CALL DEFINE 
 CALL GRIDSETUP 
 CALL START  

 CALL CPU_TIME(ALLBEGIN)
 
 ! DO WHILE ( USUM>TOL.OR.ABS(CSUM)>TOL.OR.VSUM>TOL.OR.TSUM>1E-9 )   
  !  DO WHILE ( TSUM>1E-10)   
   DO WHILE(OUTCOUNTER<1)
    !CALL CPU_TIME(TIMEBEGIN)
	CALL UPDATEPRESSURE
	CALL DENSE 
        CALL BOUND  	   
	CALL XVELOCITY  
	CALL YVELOCITY
	!CALL MIM
	CALL PRESSURE 	
	CALL OTHERPHI   
	!CALL CPU_TIME(TIMEEND)	
    OUTCOUNTER=OUTCOUNTER+1

    IF(MOD(OUTCOUNTER,1)==0)THEN
    WRITE(*,"('U:',E15.6,5X,'V:',E15.6,5X,'CSUM:',E15.6,5X,'TSUM:',E15.6,5X,I5,8X,&
                          &'MONITOR:',F14.10,1X,F14.10,1X,F14.10,1X,F14.10)")&
        &USUM,VSUM,CSUM,TSUM,OUTCOUNTER
	ENDIF

  ENDDO


CALL CPU_TIME(ALLEND)


CALL OUTPUT
   


WRITE(*,*)" THE PROCEDURE HAS COST YOU",ALLEND-ALLBEGIN,"TIME"


END

 

  

	   
	  
     

	 




